### ISSUE TITLE
Freyr Sword problems

### ISSUE THREAD

**Issue by TheBloodSwiper** [mariumbacchus/Soulslike-Weaponry#13]
Note: I'm playing the Medieval Minecraft modpack on a server.
- Disconnecting and reconnecting makes you unable to retrieve the sword and it will pop back into your inventory after 20-30 minutes of gameplay. 
- Traveling to the Aether biome made my Freyr disappear. It reappeared after about an hour, and poped back into my inventory after about 20-30 minutes.
- When the Freyr sword pops back to my inventory, it loses the enchantment I gave it, which really sucks as the sword won't be able to keep up with the mobs I have it fight against if I can't enchant it.

**Comment by mariumbacchus** [comment]
The first issue is "fixed". Now it will properly stand still when disconnecting and reconnecting instead of following the user even when the connection has been severed. Secondly, the Freyr Sword is an entity, and entities can travel through portals, but when it is not rendered, Minecraft will have a hard time locating it, especially in other dimensions. If you want to make it so it cannot enter portals, I can do that, since that seems to be the key issue here.
I'll see what I can do about enchantments being lost, will be fixed.
