### ISSUE TITLE
Add permafrost damage bonus to friends and foes wildfire

### ISSUE THREAD

**Issue by NolanHewitt** [mariumbacchus/Soulslike-Weaponry#138]
I noticed permafrost does extra damage to hot mobs like blaze and magma cubes, but not to modded mobs matching that description. Could the wildfire be added to the list of mobs effected by this damage bonus, or perhaps implement a tag based system for users to select which mobs it applies to so you don't have to add them yourself?

**Comment by mariumbacchus** [comment]
The damage bonus is handled by minecraft's own code since the Leviathan Axe does "freezing" damage, the same damage type done when in powdered snow. You have to ask the developer who added the Wildfire yourself if they can add it to the tag that contains entities that take bonus damage from freezing.
