### ISSUE TITLE
souls-like weaponry won't do right click charge attacks?

### ISSUE THREAD

**Issue by equinoxvee** [mariumbacchus/Soulslike-Weaponry#139]
the only mods i got are the rpg class mods, souls-like weaponry, bosses of mass destruction, better combat, and the pufferfish skill tree and its simple skill addon. but the weapons from souls-like weaponry won't charge their right click charge attacks. instead its like im trying to right click a shield without a shield or opening a door without a door. its just moving the arm. not charging the right click charge. any fixes or solutions? i mean i don't have to play with the charge effects, but it also makes most of the weapons useless.

**Comment by mariumbacchus** [comment]
Most likely one of your other mods causes the issue, I am guessing it's rpg class mods. Make sure to whitelist soulslike weaponry items in their (the other mods') configs so weapon abilities don't get overwritten by the other mods. There was an issue with a spellcasting mod previously that also overwrote the weapon abilities because you could apply custom spells to your weapons through that mod.
