### ISSUE TITLE
[BUG] Crash as on triggering World Creation Menu.

### ISSUE THREAD

**Issue by Dumpling00** [mariumbacchus/Soulslike-Weaponry#154]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
Fabric: 0.15.11
Soulslike-Weaponry: 1.1.4.1

**Describe the bug**
Really not sure, it just suddenly crashes on World Creation (can't even reach the menu to input seed, world name etc.)

**Add logs**
(https://gist.github.com/Dumpling00/81242337c381f348ddf04d2ce3370159)

**Other mods or relevant info**
Worth noting I am using Terrablender, Lithostitch, and a bunch of other biome mods, but Marium works perfectly in the version prior to this one.

If we could have a hotfix for this, please :(

**Comment by mariumbacchus** [comment]
Are you sure this is not an issue with all those world creation mods? Because all this mod has are json files/datapack that adds the ores. If it crashes just because of a datapack that adds ores, then I'm not sure this is something I can fix. Correct me if I'm wrong though, if you ask the other devs and they say there is something I can do.

**Comment by Dumpling00** [comment]
We've fixed that - sorry! It wasn't caused by Marium, but a datapack restricting Marium's Ores to a certain type of land - 🙏 Thank you either way and sorry for the trouble!

**Comment by mariumbacchus** [comment]
Ah that's great, no problem, glad you figured it out!
