### ISSUE TITLE
[BUG]Darkin Scythe is Buggin

### ISSUE THREAD

**Issue by NoRestForWicked** [mariumbacchus/Soulslike-Weaponry#156]
Minecraft: 1.20.1
Fabric: 0.15.11
Soulslike-Weaponry: 1.1.4.1

The Darkin scythe is bugging out alot

You might have to ctrl+f and find where I crashed in the logs

Log: [latest.log](https://github.com/user-attachments/files/16500305/latest.log)

To reproduce, all steps in the video

Video Link: https://youtu.be/5l1zQNIyVhI

**Comment by mariumbacchus** [comment]
Thanks for the video, was really helpful. I think you are glitching due to a miss communication between the client and the server. I'll look into a fix.

**Comment by NoRestForWicked** [comment]
No problem, thank you :D
Is there an explanation for the crash?

**Comment by mariumbacchus** [comment]
Still not sure, the log only mentions some errors with a lifesteal (?) mod and only you or your friend disconnecting. The fact that he glitches out/rubberbands has to do something with the client not communicating with the server properly is my guess. The crash may be due to overload of packets. I was also aware of the cooldown not applying issue, was just too lazy to fix it since the damage would be reduced heavily when not wielding a scythe and exiting. Will be fixed next patch.

**Comment by NoRestForWicked** [comment]
Ah, gotcha. Yeah I know what the log is saying about the lifesteal bug, we can't really fix it as of right now but it is COMPLETELY seperate to the scythe. That bug has to do with a certain armor and resetting heart counts if someone is wearing it.

**Comment by mariumbacchus** [comment]
Good news, managed to recreate the crash myself. Really random when it happens, but I think I know what caused it and I think I managed to fix it. The attack speed was a typo and has been fixed, also made it give the Cooldown effect instead of on item. I am also working on a fix that makes the user during Umbral Trespass completely invisible to everyone and not just himself.

**Comment by NoRestForWicked** [comment]
The AMAZING news, I cant tell you how inconvenient it is when you're mid fight and use an ability and it just domes both players lol

**Comment by mariumbacchus** [comment]
Yep, changes will be live next patch.
