### ISSUE TITLE
[BUG] Shadow Assassin Scythe's Umbral Trespass doesn't work

### ISSUE THREAD

**Issue by f-loading** [mariumbacchus/Soulslike-Weaponry#158]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
Fabric: 0.15.11
Soulslike-Weaponry: 1.1.3

**Describe the bug**
Either the Shadow Assassin Scythe's Umbral Trespass is broken or the keybind doesn't work, I'm pressing the use ability keybind while attacking something and nothing is happening, I know that the keybind isn't broken for other weapons cuz I'm able to use their abilities just fine

**Comment by mariumbacchus** [comment]
There are some known issues with both scythes now, but they are still usable. So both Darkin Scythe and Shadow Assassin Scythe does not work for you, even after attacking and then readying the weapon (wait for the attack bar to fill up) to then use? Could you have any other mod installed that could cause this issue?

**Comment by NoRestForWicked** [comment]
Make sure you've waited for the cooldown because you cannot use the ability until after the cooldown finished

**Comment by mariumbacchus** [comment]
Will close this soon if no response is given.

**Comment by f-loading** [comment]
i mean it works, just very rarely, it only works after like the 5th or 6th hit on an enemy (making the ability useless for anything weaker than a buffed up player or a mob like an iron golem), and even then it doesnt always activate the ability

**Comment by f-loading** [comment]
misclick

**Comment by mariumbacchus** [comment]
Better combat makes the item not able to right click with unless the action bar is completely filled (attack speed bar). There are also the conditions about whether you are in range of the target and the cooldown on the item. I suggest downloading the latest patch and testing with that one too. If you were using better combat, then there is nothing I can do about that since it locks the use function out during attacking. If you are still encountering the error in the newest patch, make a new post.
