### ISSUE TITLE
Throwable weapons (Leviathan Axe & Mjolnir) not returning to player hand

### ISSUE THREAD

**Issue by KB-Q** [mariumbacchus/Soulslike-Weaponry#16]
When the Leviathan Axe and Mjolnir return mid-air without hitting a block or mob, they don't go back to the player hand, but instead just circle around the player.
Only way I've found to stop this is to get rid of the entity using the /kill command. This is extremely annoying and makes those weapons useless in survival.

**Steps to recreate:**
Throw the Leviathan Axe / Mjolnir at something far away, making sure it doesn't hit a block or mob
Wait for it to return
It won't return to the player's hand, instead will start circling the player

Mod version: 0.9.8
Minecraft version: 1.19.2

**Comment by KB-Q** [comment]
I may be wrong, but I have a gut feeling it might have to do with simulation distance. I usually play with SD set to 5 chunks, so projectiles like arrows and wither skulls will freeze in place when they hit the simulation border. 

I feel this issue might be due to the same. The axe and hammer make it to the simulation border and just turn back, but they haven't hit a block or mob so their AI gets messed up... Something like that

**Comment by mariumbacchus** [comment]
I seems I am unable to recreate the issue. I believe the issue is that the return speed is too high so it zooms past the player, then, if the player is jumping and running around, it has a hard time returning to the player's location. Either the speed is the issue, or you simply had full inventory. I will reduce the return speed and see if that helps.
