### ISSUE TITLE
[FEATURE]Config option for whether or not shields should be able to be used with Ultra Heavy weapons 

### ISSUE THREAD

**Issue by NoRestForWicked** [mariumbacchus/Soulslike-Weaponry#163]
Just a config to help balance some ultra heavy weapons

Config option that disables equipping or having shields in your offhand while holding an ultra heavy weapon

A possible solution is making it a config for each weapon, but either one is good 👍

**Comment by NolanHewitt** [comment]
Are you using better combat? Because I think your issue may be from that mod instead. I tested this mod on its own and you can use a shield with any of its melee weapons. With better combat some weapons are two handed weapons, and with two handed weapons you can't use your offhand for other stuff while using that weapon.

**Comment by NoRestForWicked** [comment]
This is not an issue, It is simply a request for the ability to DISABLE the usage of shield when using an ultra heavy weapon. Think about it... you're holding a HUGE mace with one hand... using a shield seems a little out of that realm lol. It's a minor thing that I could really care less about having, but a few people on my server suggested it and I thought it wasn't the worst idea :D

**Comment by NolanHewitt** [comment]
You actually can do that, but its through better combat, you just have to set those weapons to use a different animation/combat set with a datapack. For example, to change the raw iron sword you would make a datapack with the path data\soulsweapons\weapon_attributes\guts_sword.json and change the content inside to something like this:

{
    "parent": "bettercombat:sword"
}

**Comment by NoRestForWicked** [comment]
Ah, thank you. But is there a way I can disable better combats attacks? I want the vanilla attacks to stay

**Comment by mariumbacchus** [comment]
Will add a config line. (as you now know) Better Combat already adds this, so I didn't think it was necessary, but it seems like a good idea having it on it's own so will do.

**Comment by NoRestForWicked** [comment]
While you're at it, for minor convenience do you think you could add "Can break shields" as well? just for more range on what is configurable  :D

**Comment by mariumbacchus** [comment]
Implemented for next update. Ultra Heavy weapons now shield break by default, and (while config line is true) disables offhand if heavy is in main hand. There was a bug where having heavy in offhand removed the item completely, so instead of disabling offhand if heavy is in offhand, it gives mining fatigue while main hand is occupied.
