### ISSUE TITLE
Game crashes whenstarting on forge

### ISSUE THREAD

**Issue by MediateTaxBR** [mariumbacchus/Soulslike-Weaponry#165]
Minecraft
 [1.18.2] SW-1.1.4.3 forge

**Describe the bug**
Game crashes when starting.

**Add logs**
"The game crashed whilst rendering overlay
Error: Java.lang.IllegalArgumentException: Failed to create model for minecraft:drowned"
Exit code: -1

(The mob, this time minecraft:drowned, chenges each time I try to run the game, I am not using any other mod)
![17234103087284651688037721833219](https://github.com/user-attachments/assets/8cf9919a-d921-4e7e-bc0c-8c27a419311c)

**Comment by mariumbacchus** [comment]
Reminder that you still need Geckolib and projectile damage mod installed, and make sure both of the mods you downloaded are for forge. Make sure to have at least the recommended forge version (40.2.0), but preferably the latest one (40.2.21 last time I checked). 

I just tested this with SW 1.1.4.3, geckolib forge 3.0.57, projectile damage forge 3.1.0 and forge 40.2.21, and it all worked fine. If you've made sure that all versions are right, but it still doesn't work, try allocating more RAM since Forge eats that up for breakfast. Hope this helps!
