### ISSUE TITLE
[BUG] Doesn't work with Sinytra Connector (1.20.1 and Latest Release)

### ISSUE THREAD

**Issue by Mqony** [mariumbacchus/Soulslike-Weaponry#167]
**Minecraft, modloader and mod versions**
Minecraft: 1.20.1
Fabric: 0.15.9
Soulslike-Weaponry: 1.1.3

**Describe the bug**
Game crashes due to entrypoint stage 'main'. It seems like Marium's Soulslike Weaponry is using the Forge version of Geckolib, preferring it over Fabric version which it needs.

**Add logs**
[crash-2024-08-11_20.46.04-client.txt](https://github.com/user-attachments/files/16577200/crash-2024-08-11_20.46.04-client.txt)

**To Reproduce**
2. Click on/use '....'
3. See error

**Expected behavior**
Game working fine

**Other mods or relevant info**
Sinytra Connector, using Geckolib Fabric and Forge at the same time. They work fine together, and I can have both installed without crashing. It seems like Marium's Soulslike Weaponry is using the Forge version of Geckolib, preferring it over Fabric version which it needs.

**Comment by Empmortakaten** [comment]
I am running into the same issue with the latest version.
[crash-2024-08-13_11.43.32-client.txt](https://github.com/user-attachments/files/16602059/crash-2024-08-13_11.43.32-client.txt)

**Comment by mariumbacchus** [comment]
No, the mod needs the fabric version of geckolib, it cannot and will not use forge geckolib. Issues will arise when both of them are installed since it doesn't know which one to pick. Issues with sinytra connector is not something I can fix, unless the devs over there specify what the issues are and how I can fix them/implement the features in a different way so it works with the connector. I am making the forge version of the mod for a reason, not a lot of it's content can easily be "translated".

**Comment by muon-rw** [comment]
Migrating from Geckolib to Azurelib would be enough, it has no issues with cross-platform compatibility. 

That said, this issue https://github.com/Sinytra/Connector/issues/231 was closed on the Connector github, presumably either because the 4.5+ multiloader rework of Geckolib (for 1.20.6+) *also* fixes cross-platform compatibility, or the 1.21 version of Connector has some other workaround. 

I'm not sure it's worth the effort of migrating just for one version.

**Comment by JackieJK** [comment]
This is a version of Marium's Soulslike Weaponry and GeckoLib on Forge 1.20.1 that I compiled. It needs to be used in conjunction with Sinytra Connector.
这是我基于forge1.20.1编译的一个版本  里面含有GeckoLib 需要配合信雅互联使用

https://pan.quark.cn/s/987cfacab79a

**Comment by Mqony** [comment]
@JackieJK Could you upload it on a better website?

**Comment by JackieJK** [comment]
> @JackieJK Could you upload it on a better website?

[soulslike-weaponry and geckolib patched.zip](https://github.com/user-attachments/files/16655600/soulslike-weaponry.and.geckolib.patched.zip)

**Comment by JackieJK** [comment]
> @JackieJK Could you upload it on a better website?

By the way, it wasn't tested 100%.

**Comment by MistifyedOne** [comment]
It's working well so far! Thanks a lot

**Comment by Mqony** [comment]
It's working much better so far, the game loads well and doesn't crash. However, a lot of the weapon textures are missing and I think it may be the same for bosses

**Comment by alarmgoose** [comment]
Getting this crash with the newest forge version of the mod. Seems to be a issue with Better End.

[crash-2024-08-23_22.48.08-client.txt](https://github.com/user-attachments/files/16734987/crash-2024-08-23_22.48.08-client.txt)

**Comment by mariumbacchus** [comment]
Hopefully fixed with the latest patch. Make a new post if the issue persists.
