### ISSUE TITLE
[FEATURE] Rework the model/texture of the Old Champions Remains

### ISSUE THREAD

**Issue by KiraKayn** [mariumbacchus/Soulslike-Weaponry#185]
**Is your feature request related to a problem? Please describe.**
- Theres no specific problem with it, It just simply doesnt look worthy of being in the mod when compared to other entities.

**Describe the solution you'd like**
- I think it could have a completely new design, it might require some new abilities too idk, but the Abyss Watcher boss from Dark Souls 3 has a pretty fitting look for this boss, they are also in a grave just like OCHR, they also use a sword.
 
**Describe alternatives you've considered**
- If you dont like the Abyss Watchers, I think the Death Knights from Elden Ring or Slave Knight Gael with a few changes might be good also.
**Additional context**
- Here are a few jmages of the 3 bosses I mentioned:
- Slave Knight Gael
![Slave_Knight_Gael_Concept_Art](https://github.com/user-attachments/assets/b9797f8b-1b48-457f-9a23-4df1b29eeea2)
- Abyss Watchers
![Abyss_Watcher_Artwork (1)](https://github.com/user-attachments/assets/405e8e0e-9d8d-4b0f-b85b-281ad3048a36)
- Death Knight
![maxresdefault](https://github.com/user-attachments/assets/0d48b8ae-6406-46a2-8e4e-3cdfe4e2fc7e)

**Comment by mariumbacchus** [comment]
I see your point, however it strays away from my original view of the character. The boss is kinda supposed to look like a basic draugr/skeleton type of guy. The idea is that the true soul of the Fallen Icon was cast away and looked for a new host. It stumbled upon an old grave and possessed it's body. This is the reason why it looks basic, it is possessed by the Frenzied Shade, which also looks kinda plain due to me wanting it to look as much as a soul as possible. It is not meant to be a big final guy like The Decaying King, it is supposed to be a middle-step to get to the Fallen Icon boss fight.

Before I reworked his move-set, he only had like 2 unique attacks, a thrust and a shield bash. Other than that, he just ran at you like any other mob and whacked at you with his sword. It wasn't really interesting so I re-made the fight and added lot's of other cool attacks.

I am planning on adding at least 1 other major boss that comes after the Day Stalker and Night Prowler, where the design will be heavily inspired by Abyss Watchers, Gael and other nimble. but hard hitting sword fighters with big spectacle attacks. It will be a long while before I get to make that one though, I am only in the idea phase of it's move-set.

Again, I appreciate your feedback, but it will also just take too much time. Like you mentioned, I'd have to remake all the animations to fit the new model, and then re-program all the attacks so they also are synced with the animations. I am happy with how he currently looks. If other people decided to rework the model, then I'd be happy to check it out and consider pursuing this further, but sadly I will not remake him myself.

**Comment by KiraKayn** [comment]
I completely understand, thanks for the "spoiler", Im curious how that boss will turn out, and also thank you for the quick answer.
