### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Rogenar** [mariumbacchus/Soulslike-Weaponry#4]
With the new updated version, mjolnir errors are gone. Leviathan ax can be thrown like mjolnir and returned to the hand again. But the damage of mjolnir is still very low and I don't know how to adjust it. Is it possible to fix leviathan ax and mjolnir base damage to 12 with the next update?

**Comment by mariumbacchus** [comment]
If I were to increase the damage of Mjolnir, I would have to increase the damage of every other weapon as well, resulting in every weapon outclassing Netherite Swords by a way bigger margin than I want. In short, I will not increase it to 12, but maybe buff the damage a bit later down the line.

Since you don't know how to increase the damage, I'll explain it to you here. If you go in the .minecraft folder (in %appdata%), just like you how can find a folder with the name "mods", "saves", and  "resourcepacks", there is a folder with the name "config". If you enter that folder, you may find a file named "soulsweapons.json". This is the config file. If you open this file in notepad or something else (like vscode), you can see all the properties you can edit. Look for the line that reads "mjolnir_damage" and edit the number after to whatever number you'd like. In older versions, it would be 8, but now if the config is freshly made with the new update, it should say 9. You can edit this to 12 to make the damage of Mjolnir to 12.

**Comment by Rogenar** [comment]
Would it be better to increase it from 8 to 10?

**Comment by mariumbacchus** [comment]
If you're talking about doing it through the config, then that is entirely up to you. I am considering setting the damage to 10 myself since the Leviathan Axe also has 10 now, so sounds balanced to me.

**Comment by Rogenar** [comment]
So will Mjolnir's damage be 10?

**Comment by mariumbacchus** [comment]
If you change it yourself, then yes.
