### ISSUE TITLE
The Harbinger of Moonlight might just be unbalanced...

### ISSUE THREAD

**Issue by Nickk190** [mariumbacchus/Soulslike-Weaponry#85]
I just can't kill the Harbinger of Moonlight even with totems, his first "stage" is easy, but after half health he's practically impossible to kill. I'm testing the bosses out in creative to see the best way to kill them, so when I play on my hardcore world I know the best strategies. Anyways this boss appears too difficult for me. I'm just hoping its a "skill issue" so I can grind to get better haha. But to me it seems impossible to kill the thing. I would appreciate if anyone could give me tips on how to fight Harbinger, he is immune to projectiles but getting close is a lost cause. I don't run any other OP mods that give 12-20 damage single wield weapons, just AdventureZ and Soulslike-Weaponry. I think Soulslike has a really well balanced weapon system though, done better than other mods that give 20 damage single wield weapons. What weapon in this modpack is the best for fighting the boss though? Important to note I am running a hardcore world so keep that in mind with your suggestions. Would appreciate any replies.

**Comment by mariumbacchus** [comment]
In my own testing I ran full netherite with protection 4 and around 30 golden apples, so I balanced the damage around that. He doesn't have that many openings, but the most noticeable has to be his Moonfall attack (where he charges and smashes the ground) and core beam attack. Running around on a large battlefield is key, but don't run too far away because then he will spam you with moonlight projectiles. I think I used Nightfall (with the shield ability) and rage blade (for great dps) with both sharpness 5 and unbreaking 3, and with that it was very doable, but you can't lower your guard and stand still, his attacks may be slow, but are very hard hitting.

If you have further issues, you can try to increase the cooldown time between the attacks in the config, or reduce his damage/increase the weapon damage. Hope any of this helps!
